language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: "Install"
      name: "Install dependancies"
      script: npm ci
    - stage: "Build"
      script: npm run build
      name: "Build artefact"
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_DEFAULT_REGION
  bucket: $AWS_S3_BUCKET_NAME
  local_dir: public
  skip_cleanup: true
  acl: public_read
notifications:
  email:
    recipents:
      - $ADMIN_EMAIL
    on_success: always
    on_failure: always
