language: node_js
node_js:
  - "6"
sudo: required
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - python2.7
install:
  - bundle install
  - npm install
script:
  - gulp res-images
  - gulp build-all
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_DEFAULT_REGION
  bucket: $AWS_S3_BUCKET_NAME
  local_dir: _site
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
notifications:
  email:
    - $ADMIN_EMAIL
  on_success: always
  on_failure: always
