language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm run lint
  - npm run build #use your build script

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    bucket: $AWS_S3_BUCKET_NAME_MASTER
    local_dir: public
    skip_cleanup: true
    acl: public_read
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    bucket: $AWS_S3_BUCKET_NAME_DEVELOP
    local_dir: public
    skip_cleanup: true
    acl: public_read
    on:
      branch: develop

notifications:
  email:
    recipients:
      - $ADMIN_EMAIL
    on_success: always
    on_failure: always
