version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm ci --production
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm t

artifacts:
  base-directory: public
  files:
    - "**/*"

cache:
  paths:
    - .cache
