name: Deploy

on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Build
        run: npm run build

        # Dev
      - name: Set dev AWS credentials
        if: github.ref == 'refs/heads/develop'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Deploy to dev
        if: github.ref == 'refs/heads/develop'
        run: |
          aws s3 sync public/ s3://${{ secrets.DEV_S3_BUCKET }} --delete --acl public-read --follow-symlinks

      # Prod
      - name: Set prod AWS credentials
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Deploy to prod
        if: github.ref == 'refs/heads/master'
        run: |
          aws s3 sync public/ s3://${{ secrets.PROD_S3_BUCKET }} --delete --acl public-read --follow-symlinks
